blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/CONTRIBUTING.md
    about: Check this for contributing guidelines.
